all:
	g++ test1.daemonCheck.cpp -o check
	g++ test2.daemonBattery.cpp -o battery
	g++ test3.daemonBrigthness.cpp -o display
	g++ test4.daemonShutDown.cpp -o powerOff

clean:
	rm check battery display powerOff
