/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p SetProperty ofono.xml org.ofono.CallVolume
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "SetProperty.h"

/*
 * Implementation of interface class OrgOfonoCallVolumeInterface
 */

OrgOfonoCallVolumeInterface::OrgOfonoCallVolumeInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgOfonoCallVolumeInterface::~OrgOfonoCallVolumeInterface()
{
}

